stages:
  data_processing:
    cmd: python -m src.data_processing
    deps:
      - data/card_transdata.csv
      - src/data_processing.py
    outs:
      - data/X_train.csv
      - data/y_train.csv
      - data/X_test.csv
      - data/y_test.csv

  train:
    cmd: python -m src.train
    deps:
      - data/X_train.csv
      - data/y_train.csv
      - src/train.py
    outs:
      - model/model.joblib

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - data/X_test.csv
      - data/y_test.csv
      - model/model.joblib
      - src/evaluate.py
    metrics:
      - metrics.json:
          cache: false